### ISSUE TITLE
Issue when trying to netboot any images

### ISSUE THREAD

**Issue by DatenThielt** [bruienne/bsdpy#11]
Good afternoon all,

We are trying to migrate away from our mac servers,  running BDSPY on a ubuntu machine. 

So far we have everything seemingly set up correctly,  The logs show our image is hosted and our mac's can see the image on the network.  When our mac tries to boot, it starts up with the loading globe,  Then a short loading bar that gets about 1/3 done before an error on the mac appears stating an error has caused the mac to restart.

If we boot into the image in Single user mode,  there is one section the whole process fails on before restarting,

installGTK: GTK installed
KDISocket::Connect sock_connect() returned 61
KDIHTTPBackingStore::_connectToServer connect() attempt 1 returned 61
KDISocket::Connect sock_connect() returned 61
KDIHTTPBackingStore::_connectToServer connect() attempt 2 returned 61
KDISocket::Connect sock_connect() returned 61
KDIHTTPBackingStore::_connectToServer connect() attempt 3 returned 61
KDISocket::Connect sock_connect() returned 61
KDIHTTPBackingStore::_connectToServer connect() attempt 4 returned 61
KDISocket::Connect sock_connect() returned 61
KDIHTTPBackingStore::_connectToServer connect() attempt 5 returned 61

Then it reboots,
I have googled and been unable to find what 61 is,  Any help would be greatly appreciated! 

Let me know if any additional information is needed

**Comment by macmule** [comment]
@DatenThielt HTTPS?
